[package]
name = "state-management"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gloo = "0.10.0"
gloo-storage = "0.3.0"
web-sys = "0.3.65"
yew = { version = "0.21.0", features = ["csr"] }
